"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from glob import glob

APP = ['ptunes.py']
DATA_FILES = [
       ('images', glob('images/*.png')), 
        ]
OPTIONS = {'argv_emulation': True,
 'iconfile': 'pebble.icns',
'plist': {'CFBundleShortVersionString':'1.0.0',}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
